<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <ContentTargetFolders>.</ContentTargetFolders>
    <Product>TB.SimpleRedirects.Core</Product>
    <PackageId>TB.SimpleRedirects.Core</PackageId>
    <Title>TB.SimpleRedirects.Core</Title>
    <Description>Core code for the SimpleRedirects project.</Description>
    <Authors>Tim</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/TimBoonstra/SimpleRedirects</PackageProjectUrl>
    <PackageTags>umbraco plugin package</PackageTags>
    <PackageIconUrl>https://raw.githubusercontent.com/TimBoonstra/SimpleRedirects/v9/main/package/simpleRedirectsLogo.png</PackageIconUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="17.0.0" />
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="17.0.0" />
  </ItemGroup>
</Project>
